site_name: Declerative Slides Docs
site_url: https://github.com/AlexTesta00/PPS-24-declarative-slides/docs/
use_directory_urls: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.expand
    - content.code.focus
    - content.code.inherit
    - content.tabs.link
    - content.tabs.sticky
    - content.tooltips
    - content.toc.sticky
    - content.toc.follow
    - content.toc.highlight
    - content.toc.deep
    - content.toc.indent
    - content.toc.collapse
    - content.toc.expand
    - content.toc.sections
    - content.toc.smooth_scroll
    - content.toc.scrollspy
    - content.toc.scrollspy_offset

nav:
  - Introduzione: index.md
  - Dominio: domain.md
  - Obiettivi: goals.md
  - Processo di sviluppo: development_process.md
  - Stack tecnologico: tech_stack.md
  - Architettura Generale: general_architecture.md
  - Design di dettaglio: detailed_design.md
  - Sviluppo iterativo e sprint: development_and_sprint.md
  - Problemi Incontrati: problem_solution.md
  - Conclusioni: conclusions.md

plugins:
  - search
  - to-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/docs.pdf
      cover_title: "PPS24-Declerative Slides"
      cover_subtitle: "Alex Testa"
      toc_title: "Indice"
      toc_level: 3
      verbose: true

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format